from __future__ import annotations

TICKER_LABELS = {
    "ACWI": "全世界株式ETF",
    "VT": "全世界株式ETF",
    "SPY": "米国大型株ETF",
    "VOO": "S&P500連動ETF",
    "IVV": "S&P500連動ETF",
    "VEA": "先進国株ETF",
    "IEFA": "先進国株ETF",
    "VWO": "新興国株ETF",
    "IEMG": "新興国株ETF",
    "EWJ": "日本株ETF",
    "XLK": "情報技術セクターETF",
    "XLF": "金融セクターETF",
    "VFH": "金融セクターETF",
    "XLE": "エネルギーセクターETF",
    "VDE": "エネルギーセクターETF",
    "XLV": "ヘルスケアセクターETF",
    "VHT": "ヘルスケアセクターETF",
    "XLY": "一般消費財セクターETF",
    "VCR": "一般消費財セクターETF",
    "XLP": "生活必需品セクターETF",
    "VDC": "生活必需品セクターETF",
    "XLI": "資本財セクターETF",
    "VIS": "資本財セクターETF",
    "XLB": "素材セクターETF",
    "VAW": "素材セクターETF",
    "XLU": "公益事業セクターETF",
    "VPU": "公益事業セクターETF",
    "XLRE": "不動産セクターETF",
    "GLD": "金ETF",
    "IAU": "金ETF",
    "AGG": "米国総合債券ETF",
    "BND": "米国総合債券ETF",
    "TIP": "米国物価連動債ETF",
    "SCHP": "米国物価連動債ETF",
    "VNQ": "米国REIT ETF",
    "REET": "グローバル不動産ETF",
    "HYG": "米国ハイイールド債ETF",
    "LQD": "米国投資適格社債ETF",
    "^VIX": "VIX指数",
    "^MOVE": "MOVE指数",
    "CL=F": "WTI原油先物",
    "BZ=F": "Brent原油先物",
    "GC=F": "金先物",
    "DX-Y.NYB": "米ドル指数",
    "ZW=F": "小麦先物",
    "ZC=F": "トウモロコシ先物",
    "WEAT": "小麦ETF",
    "CORN": "トウモロコシETF",
    "FRED:MORTGAGE30US": "米30年固定住宅ローン金利",
    "FRED:BAMLH0A0HYM2": "米ハイイールドOAS",
    "FRED:BAMLC0A0CM": "米投資適格社債OAS",
    "FRED:DFII10": "米10年実質金利",
    "FRED:T10YIE": "米10年期待インフレ率",
    "FRED:T10Y2Y": "米10年-2年金利差",
    "FRED:T10Y3M": "米10年-3カ月金利差",
    "FRED:NFCI": "シカゴ連銀金融環境指数",
    "FRED:ANFCI": "調整済みシカゴ連銀金融環境指数",
    "^TNX": "米10年金利",
    "USDJPY=X": "米ドル円",
    "EURJPY=X": "ユーロ円",
    "JPY=X": "円相場",
    "1306.T": "TOPIX連動ETF",
    "1321.T": "日経225連動ETF",
    "2510.T": "国内債券ETF",
    "1343.T": "国内REIT ETF",
    "1540.T": "純金ETF",
    "^TOPX": "TOPIX指数",
    "^SOX": "フィラデルフィア半導体指数",
    "SOXX": "半導体ETF",
}


def ticker_label_ja(ticker: str | None) -> str:
    if not ticker:
        return "-"
    return TICKER_LABELS.get(ticker, ticker)
